# Integration test harness useful for testing the GitHub Action itself

# This can be run locally using act (https://github.com/nektos/act) like this:
# act -v -j build --
# This will build the docker image that packages the GitHub Action and run it, with verbose logging to show each step in detail
name: build
on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Verify that the Docker image for the action builds
        run: docker build . --file Dockerfile
      - name: docs integration test
        # This syntax tells the test to run the current directory as a GitHub Action
        uses: ./
        with:
          action: docs
          path: ./tests/docs
          # provide ttl file names without extensions; the base file name will be
          #    used for output files with the appropriate extension.
          inputttl: 2026_06_12_TerraLID_vocab
          # these are the URIs for the ConceptScheme; there must be a conceptScheme defined in each vocabulary.
          inputvocaburi: http://vocab.terralid.org#conceptScheme_a0559f69